description = "Library for running OpenRewrite recipes against arbitrary project directories without requiring a working build system"

plugins {
    id("kotlin-convention")
    id("publishing-convention")
    id("dokka-convention")
    `java-library`
}

dependencies {
    // OpenRewrite BOM + modules
    // rewrite-core is 'api' because callers use Result, SourceFile, Recipe, etc. directly
    api(platform(libs.rewrite.recipe.bom))
    api("org.openrewrite:rewrite-core")
    implementation("org.openrewrite:rewrite-java")
    implementation("org.openrewrite:rewrite-java-21")
    implementation("org.openrewrite:rewrite-java-25")
    implementation("org.openrewrite:rewrite-yaml")
    implementation("org.openrewrite:rewrite-json")
    implementation("org.openrewrite:rewrite-xml")
    implementation("org.openrewrite:rewrite-properties")
    implementation("org.openrewrite:rewrite-kotlin")
    implementation("org.openrewrite:rewrite-groovy")
    implementation("org.openrewrite:rewrite-maven")
    implementation("org.openrewrite:rewrite-toml")
    implementation("org.openrewrite:rewrite-hcl")
    implementation("org.openrewrite:rewrite-protobuf")
    implementation("org.openrewrite:rewrite-docker")
    // rewrite-gradle is not in the BOM — pin explicitly to match rewrite-core version
    implementation(libs.rewrite.gradle)

    // Maven model (pom.xml parsing in Stage 2)
    implementation(libs.maven.model)

    // Maven Resolver (JAR download for Stage 2 + recipe artifacts)
    implementation(libs.maven.resolver.api)
    implementation(libs.maven.resolver.impl)
    implementation(libs.maven.resolver.supplier.mvn3)

    // Config + JSON report
    implementation(libs.jackson.dataformat.yaml)
    implementation(libs.jackson.module.kotlin)

    // Tests
    testImplementation(libs.logback.classic)
    testImplementation(libs.kotest.runner.junit5)
    testImplementation(kotlin("test"))
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Generate BuildPluginVersions.kt from the version catalog so the upstream rewrite-maven-plugin /
// rewrite-gradle-plugin versions can be bumped by Dependabot via gradle/libs.versions.toml instead
// of being hardcoded in Kotlin source.
val generatedPluginVersionsDir =
    layout.buildDirectory.dir("generated/sources/pluginVersions/kotlin/main")

val generatePluginVersions by tasks.registering {
    val gradlePluginVersion = libs.versions.rewrite.gradle.plugin.get()
    val mavenPluginVersion = libs.versions.rewrite.maven.plugin.get()
    val outDir = generatedPluginVersionsDir
    inputs.property("gradlePluginVersion", gradlePluginVersion)
    inputs.property("mavenPluginVersion", mavenPluginVersion)
    outputs.dir(outDir)
    doLast {
        val pkg = outDir.get().asFile.resolve("io/github/skhokhlov/rewriterunner/config")
        pkg.mkdirs()
        pkg.resolve("BuildPluginVersions.kt").writeText(
            """
            // Generated by the `generatePluginVersions` Gradle task — do not edit.
            // Source of truth: gradle/libs.versions.toml (so Dependabot can bump these).
            package io.github.skhokhlov.rewriterunner.config

            internal object BuildPluginVersions {
                const val REWRITE_GRADLE_PLUGIN_VERSION: String = "$gradlePluginVersion"
                const val REWRITE_MAVEN_PLUGIN_VERSION: String = "$mavenPluginVersion"
            }
            """.trimIndent() + "\n",
        )
    }
}

kotlin.sourceSets["main"].kotlin.srcDir(generatePluginVersions.map { generatedPluginVersionsDir })
