name: Publish to Maven Central

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # needed for git describe

      - uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Publish
        run: ./gradlew publish
        env:
          GITHUB_REF: ${{ github.ref }}
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_TOKEN: ${{ secrets.CENTRAL_PORTAL_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}

      - name: Generate Dokka HTML docs
        run: ./gradlew dokkaGenerate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/dokka/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
